// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class DonateMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DonateMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDonateMessage(bb:flatbuffers.ByteBuffer, obj?:DonateMessage):DonateMessage {
  return (obj || new DonateMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDonateMessage(bb:flatbuffers.ByteBuffer, obj?:DonateMessage):DonateMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DonateMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

money():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

mutate_money(value:number):boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);

  if (offset === 0) {
    return false;
  }

  this.bb!.writeFloat64(this.bb_pos + offset, value);
  return true;
}

static startDonateMessage(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addMoney(builder:flatbuffers.Builder, money:number) {
  builder.addFieldFloat64(0, money, 0.0);
}

static endDonateMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDonateMessage(builder:flatbuffers.Builder, money:number):flatbuffers.Offset {
  DonateMessage.startDonateMessage(builder);
  DonateMessage.addMoney(builder, money);
  return DonateMessage.endDonateMessage(builder);
}
}
