name: Node.js CI

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install node.js
        id: node-install
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          # cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
          check-latest: false

      - name: install pnpm
        id: pnpm-install
        uses: pnpm/action-setup@v2
        with:
          version: 7.20.0
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install dependencies
        run: pnpm --recursive install

  # run-tests:
  #   runs-on: ubuntu-latest
  #   needs: [install-dependencies]

    # steps:
      - uses: actions/cache@v3
        name: restore pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.PNPM_STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: run tests
        run: pnpm --recursive test