name: Node.js CI

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.20.0
      - uses: actions/setup-node@v3
        with:
          # node-version: 19.3.0
          node-version-file: 'package.json'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
          check-latest: false

      # - name: Checkout
      #   uses: actions/checkout@v3

      # - uses: pnpm/action-setup@v2
      #   name: Install pnpm
      #   id: pnpm-install
      #   with:
      #     version: 7.20.0
      #     run_install: false

      # - name: Get pnpm store directory
      #   id: pnpm-cache
      #   shell: bash
      #   run: |
      #     echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      # - uses: actions/cache@v3
      #   name: Setup pnpm cache
      #   with:
      #     path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
      #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-store-

      # - name: Install dependencies
      #   run: pnpm --recursive install

  # run-tests:
  #   runs-on: ubuntu-latest
  #   needs: [cache-and-install]

  #   steps:
  #     - uses: actions/cache@v3
  #       name: Setup pnpm cache
  #       with:
  #         path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
  #         key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pnpm-store-
  #     - name: Run tests
  #       run: pnpm --recursive test